title: "Daniel Odey"
# logo: /assets/heaadshot.png
description: "Data and BI Analyst skilled in tools like MS Excel, Google Sheet, SQL, Power BI, Python"
# show_downloads: false
theme: jekyll-theme-cayman
